'use strict';
const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/beneficiary.controller');
const authenticate = require('../middleware/authenticate');
router.use(authenticate);
router.get('/', ctrl.getAll);
router.post('/', ctrl.create);
router.patch('/:id/favourite', ctrl.toggleFavourite);
router.delete('/:id', ctrl.delete);
module.exports = router;
