apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: varad-1021-dev
  labels:
    app: postgres

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi