apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: varad-1021-dev
type: Opaque
stringData:
  DATABASE_URL: "<DATABASE_URL>"

  JWT_ACCESS_SECRET: "<JWT_ACCESS_SECRET>"
  JWT_REFRESH_SECRET: "<JWT_REFRESH_SECRET>"

  EMAIL_USER: "<EMAIL_USER>"
  EMAIL_PASS: "<EMAIL_PASS>"

  GROQ_API_KEY: "<GROQ_API_KEY>"
